import { ideasSchema, type Idea } from "./idea-schema";
import { getCurrentProjectPlan } from "./project-plans";

const crmPlan = getCurrentProjectPlan("idea-001");
const clinicPlan = getCurrentProjectPlan("idea-002");
const automationPlan = getCurrentProjectPlan("idea-003");
const leadPlan = getCurrentProjectPlan("idea-004");

if (!crmPlan || !clinicPlan || !automationPlan || !leadPlan) {
  throw new Error("Detailed ideas require trusted implementation plans.");
}

const rawIdeas: Idea[] = [
  {
    id: "idea-001",
    displayNumber: "001",
    slug: "pergola-quotation-follow-up-crm",
    title: "Pergola Quotation & Follow-up CRM",
    summary: "Organise enquiries, site visits, quotations, and installation follow-ups for specialist outdoor construction work.",
    kitTitle: "Pergola Business Kit",
    kitSummary: "Explore the example software, learn what to customise, and prepare your offer for pergola businesses.",
    solutionType: "Custom CRM",
    industries: ["Home Services", "Outdoor Construction"],
    technicalRequirements: ["TypeScript", "React", "Database configuration", "Email or SMS integration"],
    intendedCustomer: "Pergola installers, timber framing shops, and outdoor-living contractors",
    proposedBusinessModel: "One-off implementation with optional managed support",
    readiness: "Sample blueprint",
    marketEvidence: "Not yet validated",
    addedOrder: 6,
    published: true,
    detailAvailable: true,
    implementationPlanVersion: crmPlan.version,
    previewVariant: "pipeline",
    coverArt: {
      src: "/artwork/ideas/pergola-business-kit.webp",
      alt: "A timber pergola beside a table of plans, materials, and measuring tools",
      position: "50% 50%",
    },
    publicCoverArt: {
      src: "/artwork/marketing/modern/pergola-kit.webp",
      alt: "A contemporary pergola model connected to a clean digital workflow",
      position: "50% 50%",
    },
    cardNote: "Demo, source, setup guide, potential-customer list, sales kit, and delivery guide available",
    resources: [
      {
        id: "crm-demo",
        label: "Public CRM demo",
        type: "demo",
        availability: "available",
        description: "Visitor-accessible dashboard example with navigation for the observed operating sections. Individual actions and records have not been tested.",
        externalUrl: "https://universalpergola-public-demo.vercel.app/dashboard",
        actionLabel: "Open CRM demo",
        notice: "Demonstration uses synthetic data. Changes reset on reload.",
      },
      {
        id: "crm-source",
        label: "Source ZIP",
        type: "source",
        availability: "available",
        description: "Owner-supplied Universal Pergola source archive. It is an offline/UAT foundation and requires your own reviewed configuration before use.",
        downloadPath: "/app/resources/pergola-source",
        actionLabel: "Download source ZIP",
        notice: "Protected member download. The archive is not a production-ready hosted service.",
      },
      {
        id: "crm-guide",
        label: "Setup guide",
        type: "guide",
        availability: "available",
        description: "Inspected local setup, customisation, testing, deployment-preparation, handover, and backup guidance for the supplied CRM.",
        downloadPath: "/app/resources/pergola-setup-guide",
        actionLabel: "Download setup guide",
        notice: "Protected member guide. Hosted deployment and production services remain unverified.",
      },
      {
        id: "crm-discovery",
        label: "Potential customers",
        type: "script",
        availability: "available",
        description: "A protected, member-safe projection of published business research from the owner-supplied workbook.",
        downloadPath: "/app/resources/pergola-potential-customers",
        actionLabel: "Download member CSV",
        notice: "Non-exclusive research list—not confirmed buyers. Verify every business and contact route before outreach.",
      },
    ],
    featuredResourceIds: ["crm-demo", "crm-source", "crm-discovery"],
    sections: [
      {
        id: "opportunity",
        type: "overview",
        title: "The opportunity",
        body: [
          "This starter investigates a tailored CRM for pergola installers, timber-framing shops, and outdoor-living contractors that handle site enquiries, measurements, multi-option quotations, deposits, installation scheduling, and follow-up.",
          "Treat the workflow as a suggested investigation path, not a verified description of every contractor. Map the buyer’s current tools, hand-offs, delays, and ownership before proposing software.",
          "The proposed offer is a scoped CRM setup with optional support. It is not a proven commercial package: no buyer interviews, sales, live deployments, or willingness-to-pay evidence are documented in this repository.",
        ],
        friction: "Potential friction to investigate: measurements and quote options can move between inboxes, paper notes, spreadsheets, and staff, while responsibility for the next follow-up remains unclear.",
        validation: "Ask contractors to walk through recent enquiries from first contact to final outcome. Confirm where data is re-entered, which quote details change, who owns each follow-up, what customers ask repeatedly, and which mistakes have a measurable operational cost.",
        businessModel: "Proposed offer: a deliberately scoped setup and handover project, with optional hosting or support only when responsibilities, data protection, third-party costs, response times, and change limits are written down.",
      },
      {
        id: "demo",
        type: "demo-preview",
        title: "Explore the example software",
        description: "The separate public demonstration uses synthetic data and shows navigation for enquiries, customers, site visits, quotations, commercial documents, projects, payments, tasks, feedback, reports, accounts, products, and categories. Visitor access to the dashboard was verified; individual records, actions, persistence, messaging, payments, and integrations were not tested.",
        variant: "crm",
        metrics: [
          { label: "Data", value: "Synthetic" },
          { label: "Scope", value: "Navigation inspected" },
          { label: "Actions", value: "Not tested" },
        ],
        modules: ["Enquiries", "Customers", "Site visits", "Quotations", "Projects", "Payments", "Tasks", "Reports", "Products", "Categories"],
      },
      {
        id: "software",
        type: "workflow",
        title: "What the software includes",
        description: "Use these observed sections to decide which parts matter to a customer. The archive and public demo are a starting point, not proof that every action is ready for live use.",
        steps: [
          { id: "crm-enquiry", title: "Enquiries and customers", detail: "Keep contact details, requests, ownership, and the next action together." },
          { id: "crm-survey", title: "Site visits", detail: "Prepare measurements, access notes, photos, preferences, and open questions." },
          { id: "crm-quote", title: "Quotations and documents", detail: "Track options, assumptions, exclusions, approvals, sent dates, and commercial documents." },
          { id: "crm-delivery", title: "Projects and tasks", detail: "Hand accepted work into delivery with owners, tasks, scheduling constraints, and unresolved decisions." },
          { id: "crm-payment", title: "Payments and reporting", detail: "Review the included payment, feedback, account, product, category, and reporting areas before deciding what to keep." },
        ],
        safeguard: "Use fictional data while exploring. Before handling customer records, review permissions, backups, retention, message approval, and recovery responsibilities.",
      },
      {
        id: "setup",
        type: "resources",
        title: "Setup and customisation",
        intro: "Use the inspected guide with the protected source archive, then decide what to rename, remove, configure, and test for a specific pergola business. Local package checks passed; live database, hosted services, and production deployment remain separate verification work.",
        resourceIds: ["crm-source", "crm-guide"],
        steps: [
          { title: "Inspect the foundation", detail: "Review the archive locally with fictional data and record which included areas are relevant to the customer workflow." },
          { title: "Trim the scope", detail: "Choose what to keep, rename, or remove before changing branding, fields, permissions, or integrations." },
          { title: "Agree responsibilities", detail: "Write down configuration ownership, authorised integrations, backups, recovery, support boundaries, and third-party costs." },
          { title: "Test before live use", detail: "Complete customer-specific acceptance checks and production approval. The supplied package is an offline/UAT foundation, not a ready hosted service." },
        ],
      },
      {
        id: "customers",
        type: "customer-discovery",
        title: "Potential customers",
        audiences: ["Owner-operators who quote and install", "Sales or survey staff in pergola businesses", "Operations staff who receive won-work handovers", "Veranda, awning, and outdoor-carpentry specialists with comparable workflows"],
        questions: [
          "Please walk through the last enquiry that became a job. Which records and people were involved?",
          "Which measurements, options, exclusions, and approvals must be correct before a quotation is sent?",
          "How do you know which quotes are awaiting a reply, and who owns the next action?",
          "Where is information copied between email, messaging, paper, spreadsheets, accounting tools, or calendars?",
          "Which delays or mistakes have a real operational cost, and how is that cost observed?",
          "What would a useful demonstration need to reflect before it felt relevant rather than generic?",
          "Which systems must remain the source of truth, and what integrations are actually authorised?",
          "Who would maintain users, backups, templates, message rules, and process changes after handover?",
        ],
        guidance: "After interviews, write a narrow problem statement and demonstration scenario using fictional data. Define the proposed offer with inclusions, exclusions, acceptance checks, handover responsibilities, support boundaries, third-party costs, and a change process. Prepare outreach around the observed workflow—not unsupported savings or sales claims—and test interest before custom development.",
      },
      {
        id: "sales",
        type: "sales-kit",
        title: "Sales kit",
        intro: "Edit these five practical templates for one researched business at a time. Replace every placeholder with verified context and never imply prior interest, results, or urgency that you cannot support.",
        items: [
          {
            title: "Initial introduction",
            kind: "email",
            detail: "A short, respectful first message based on one verified detail—not an assumption about the company’s needs.",
            subject: "A quick question about [Company name]’s enquiry workflow",
            template: "Hi [Name],\n\nI found [Company name] through [published source] and noticed [specific, verified detail]. I’m researching how pergola businesses manage the hand-off from enquiry and site visit to quotation follow-up.\n\nI have a short fictional CRM example built around that workflow. Would a 10-minute walkthrough be useful, or is this not relevant for your team?\n\nThanks,\n[Your name]",
          },
          {
            title: "Phone opening",
            kind: "call",
            detail: "A natural 20–30 second opener that asks permission before continuing.",
            template: "Hi [Name], I’m [Your name]. I found [Company name] through [published source]. I’m researching how pergola teams handle the move from enquiry and site visit to quotation follow-up, and I have a short fictional software example. Is this a bad time for one quick question about how your team handles that today?",
          },
          {
            title: "Follow-up",
            kind: "follow-up",
            detail: "A concise follow-up that references only a message you actually sent and does not fabricate interest.",
            subject: "Following up on my note about [workflow]",
            template: "Hi [Name],\n\nI’m following up on the note I sent on [date] about [specific workflow]. I don’t want to assume this is a priority for [Company name].\n\nIf it is relevant, I can show a 10-minute fictional example covering enquiry → quotation → follow-up → delivery. If not, no reply is needed and I won’t keep chasing.\n\nThanks,\n[Your name]",
          },
          {
            title: "Demo structure",
            kind: "demo",
            detail: "A bounded walkthrough that keeps fictional data and unverified capabilities explicit.",
            template: "1. CONTEXT — Confirm [agreed workflow] and the problem the customer agreed to discuss.\n\n2. ENQUIRY — Create or open a fictional enquiry and show owner, priority, and next action.\n\n3. QUOTATION — Show the site information, quote options, assumptions, exclusions, revision state, and totals.\n\n4. FOLLOW-UP — Show how responsibility and the next follow-up stay visible. Do not claim automatic messaging unless it is configured and tested.\n\n5. PROJECT / DELIVERY — Show the handover into stages, tasks, files, payment records, and completion.\n\n6. BOUNDARY — Recap what is included in the source, what needs configuration, what was not verified, and the one agreed next step.",
          },
          {
            title: "Proposal outline",
            kind: "proposal",
            detail: "A practical scope outline with responsibilities and placeholders instead of invented commercial terms.",
            template: "CUSTOMER PROBLEM\n[Confirmed workflow and observable problem]\n\nAGREED SCOPE\n[What will be configured and tested]\n\nINCLUDED CONFIGURATION\n[Branding, roles, fields, workflow, documents, training]\n\nEXCLUSIONS\n[Integrations, migration, hosting, support, or modules not included]\n\nTIMELINE\n[Placeholder — agree dates after dependencies]\n\nPRICE\n[Placeholder — confirm currency, taxes, milestones, and validity]\n\nHOSTING AND SUPPORT RESPONSIBILITIES\n[Who owns accounts, costs, backups, recovery, credentials, and future changes]\n\nACCEPTANCE AND NEXT STEP\n[Acceptance checks, handover evidence, and one decision required]",
          },
        ],
      },
      {
        id: "delivery",
        type: "action-plan",
        title: "Delivery checklist",
        stages: crmPlan.stages,
      },
    ],
  },
  {
    id: "idea-002",
    displayNumber: "002",
    slug: "clinic-operations-crm",
    title: "Clinic Operations CRM Kit",
    summary: "A practical clinic operations system you can adapt, demonstrate, and offer to independent clinics.",
    kitTitle: "Clinic Operations CRM Kit",
    kitSummary: "Understand a clinic workflow, shape a responsible operations-software offer, and prepare a bounded implementation.",
    solutionType: "Custom CRM",
    industries: ["Clinic Operations", "Business Services"],
    technicalRequirements: ["CRM configuration", "Workflow discovery", "Access and privacy review"],
    intendedCustomer: "Independent clinics and small clinic groups with an administrative team",
    proposedBusinessModel: "Scoped operations CRM implementation with optional separately agreed support",
    readiness: "Sample blueprint",
    marketEvidence: "Not yet validated",
    addedOrder: 5,
    published: true,
    detailAvailable: true,
    implementationPlanVersion: clinicPlan.version,
    previewVariant: "pipeline",
    coverArt: {
      src: "/artwork/ideas/clinic-operations-crm.webp",
      alt: "A modern clinic reception connected to abstract appointment, profile, follow-up, and reporting cards",
      position: "50% 50%",
    },
    cardNote: "Full kit for members; demo, source, screenshots, and prospect list await owner inputs",
    resources: [
      { id: "clinic-demo", label: "Clinic CRM demo", type: "demo", availability: "not-connected", description: "Clinic CRM demo will be added after the owner supplies a URL and its visitor-accessible features are inspected." },
      { id: "clinic-source", label: "Clinic CRM source", type: "source", availability: "not-connected", description: "Source archive not supplied. No protected download is available yet." },
      { id: "clinic-setup-guide", label: "Verified setup guide", type: "guide", availability: "not-connected", description: "Exact setup steps and commands will be added only after the source archive is safely inspected and locally verified." },
      { id: "clinic-prospects", label: "Clinic prospect list", type: "worksheet", availability: "not-connected", description: "Clinic prospect list not connected yet. No businesses or contacts have been fabricated." },
    ],
    featuredResourceIds: ["clinic-demo", "clinic-source", "clinic-prospects"],
    sections: [
      {
        id: "clinic-opportunity",
        type: "overview",
        title: "Turn one clinic workflow into a repeatable software service",
        body: [
          "Independent clinics may coordinate new enquiries, appointments, follow-ups, customer or patient administration, staff tasks, payments, and day-to-day reporting across several tools.",
          "The opportunity is to understand one clinic's actual administrative process, then adapt a focused operations system around it. This is not an EHR, EMR, medical-records platform, or clinical decision system.",
          "Possible service layers include initial configuration, branding, agreed workflow changes, appropriate data import, staff onboarding, separately agreed hosting or maintenance, and additional modules later.",
        ],
        friction: "Administrative hand-offs can become difficult to see when enquiries, appointments, follow-ups, tasks, and payment status live in separate places.",
        validation: "Ask a clinic team to map its real process and confirm every status, owner, exception, permission, and system of record before proposing changes.",
        businessModel: "Possible ways to structure the service: a bounded initial configuration, customer-specific customisation and onboarding, then optional support only where ownership and responsibilities are agreed.",
      },
      {
        id: "clinic-demo",
        type: "demo-preview",
        title: "Explore the Clinic CRM",
        description: "Clinic CRM demo will be added after the owner supplies a URL. No live screens, features, or workflow have been verified in this phase.",
        variant: "crm",
        metrics: [
          { label: "Demo URL", value: "Not supplied" },
          { label: "Screenshots", value: "Not supplied" },
          { label: "Feature review", value: "Pending" },
        ],
      },
      {
        id: "clinic-software",
        type: "workflow",
        title: "Get the software",
        description: "The source archive has not been supplied. This activity records the inspection boundary and will show verified capabilities only after the actual package is reviewed.",
        steps: [
          { id: "source-receive", title: "Receive and inspect", detail: "Keep the archive outside public assets and inspect its structure, documentation, environment examples, dependencies, and licensing before executing scripts." },
          { id: "source-verify", title: "Verify in isolation", detail: "Run only appropriate local checks after static inspection, using fictional data and no hosted-service changes." },
          { id: "source-publish", title: "Publish verified scope", detail: "Describe features as included, locally verified, present but unverified, or not included—never infer them from a demo." },
        ],
        safeguard: "No source download exists until the owner supplies the archive and it passes the protected-resource review.",
      },
      {
        id: "clinic-setup",
        type: "resources",
        title: "Setup & customise",
        intro: "The exact setup guide is waiting for the source archive. For now, use this planning sequence without treating any command, infrastructure, or feature as verified.",
        resourceIds: ["clinic-source", "clinic-setup-guide"],
        steps: [
          { title: "Confirm requirements", detail: "Identify the actual runtime, package manager, backend, authentication, storage, and third-party services from the source." },
          { title: "Plan the clinic adaptation", detail: "Map branding, workflow states, staff roles, permissions, and reports before changing code or schema." },
          { title: "Test with synthetic data", detail: "Verify important administrative flows, permissions, errors, backups, and recovery without real clinic or patient information." },
          { title: "Prepare handover", detail: "Document account ownership, deployment, credentials, training, unresolved limitations, and support boundaries." },
        ],
      },
      {
        id: "clinic-prospecting",
        type: "customer-discovery",
        title: "Find clinics",
        audiences: ["Dental clinics", "Aesthetic or dermatology clinics", "Physiotherapy clinics", "Chiropractic clinics", "Wellness clinics", "Specialty clinics", "Small medical centres"],
        questions: [
          "Search one clinic category and location using public business sources.",
          "Record clinic name, website, country, city, clinic type, published business contact route, source, and last checked date.",
          "Verify each business and contact route manually before any respectful one-to-one outreach.",
        ],
        guidance: "Try focused searches such as dental clinic Dubai, aesthetic clinic Abu Dhabi, physiotherapy clinic Dubai, dental clinic London, or aesthetic clinic Manchester. The categories are discovery targets, not proof of demand. Do not scrape or invent leads.",
      },
      {
        id: "clinic-conversation",
        type: "sales-kit",
        title: "Start the conversation",
        intro: "Edit these templates for one researched clinic. Keep placeholders visible until verified, ask about the real workflow first, and make no savings, patient-volume, revenue, or compliance claims.",
        items: [
          {
            title: "Email",
            kind: "email",
            detail: "A concise first message that asks whether the administrative workflow is relevant.",
            subject: "Quick question about your clinic workflow",
            template: "Hi [Name],\n\nI was looking at [Clinic] and wanted to ask how your team currently manages appointments, enquiries and follow-ups.\n\nI've been working on a clinic operations system designed to bring those workflows into one place.\n\nIf improving that process is relevant for your team, I can show you a short demo and first understand how your current workflow works.\n\nRegards,\n[Your name]",
          },
          {
            title: "Phone",
            kind: "call",
            detail: "A short permission-based opening without implying an existing relationship.",
            template: "Hi, I'm [Name]. I wanted to ask a quick question about how your clinic currently handles enquiries, appointments and follow-ups. I've been working on a system around this type of workflow and wanted to see whether it's relevant for your clinic.",
          },
          {
            title: "Follow-up",
            kind: "follow-up",
            detail: "A respectful follow-up with no fabricated urgency.",
            subject: "Following up on my clinic workflow question",
            template: "Hi [Name],\n\nI'm following up on the note I sent on [date] about [specific administrative workflow]. I don't want to assume this is a priority for [Clinic].\n\nIf it is relevant, I can first learn how your current process works and then show only the parts of the operations example that relate to it. If not, no reply is needed.\n\nRegards,\n[Your name]",
          },
          {
            title: "Demo",
            kind: "demo",
            detail: "Use this order only after a real demo is supplied and verified.",
            template: "1. Ask about the current administrative workflow.\n\n2. Show only verified CRM features that relate to it.\n\n3. Ask what does not match.\n\n4. Explain only what can actually be customised.\n\n5. Confirm one appropriate next step and restate any unverified boundaries.",
          },
          {
            title: "Proposal",
            kind: "proposal",
            detail: "A scope structure with placeholders, not fixed commercial terms.",
            template: "CURRENT PROBLEM\n[Confirmed administrative problem]\n\nAGREED WORKFLOW\n[Current and proposed workflow]\n\nINCLUDED FEATURES\n[Verified included features]\n\nCUSTOMISATION\n[Agreed changes]\n\nEXCLUSIONS\n[Clinical records, integrations, or other work not included]\n\nDATA / IMPORT RESPONSIBILITIES\n[Ownership, preparation, validation, retention]\n\nHOSTING, TRAINING, AND SUPPORT\n[Accounts, costs, handover, response boundaries]\n\nPRICE\n[Customer-specific quotation]\n\nNEXT STEP\n[Decision and acceptance checks]",
          },
        ],
      },
      {
        id: "clinic-pricing",
        type: "pricing-planner",
        title: "Price your offer",
        intro: "Model delivery cost and projected gross margin from your own assumptions. This is a planning estimate—not a market-price recommendation.",
        packageStructures: [
          { title: "Starter implementation", items: ["Branding", "Basic setup", "Deployment", "Handover"] },
          { title: "Custom implementation", items: ["Workflow changes", "Data migration", "Additional reports or features", "Training"] },
          { title: "Managed support", items: ["Agreed hosting management", "Backups", "Maintenance", "Support"] },
        ],
      },
      {
        id: "clinic-tools",
        type: "tools",
        title: "Tools you'll need",
        intro: "The source package has not been supplied, so infrastructure requirements remain unverified. Prefer customer-owned long-term production accounts where practical and document any developer-managed account explicitly.",
        tools: [
          { name: "Codex", purpose: "Inspect and adapt code with reviewed instructions", requirement: "Optional", ownership: "Member", costNote: "Use an existing suitable plan where available" },
          { name: "Git", purpose: "Version control and change review", requirement: "Required", ownership: "Customer or shared by agreement", costNote: "Free options exist" },
          { name: "Runtime / package manager", purpose: "Install, run, test, and build the CRM", requirement: "Confirm from source", ownership: "Implementation environment", costNote: "Do not choose until source inspection" },
          { name: "Hosting", purpose: "Run the production application", requirement: "Confirm from source", ownership: "Customer-owned where practical", costNote: "Compare only after verified requirements" },
          { name: "Database / backend", purpose: "Store authorised operational data", requirement: "Confirm from source", ownership: "Customer-owned where practical", costNote: "Capacity, backups, and support affect cost" },
          { name: "Domain", purpose: "Customer-facing address", requirement: "Optional", ownership: "Customer", costNote: "Annual registration cost varies" },
          { name: "Transactional email", purpose: "System messages only if supported and agreed", requirement: "Confirm from source", ownership: "Customer", costNote: "Verify provider, consent, and volume" },
          { name: "File storage", purpose: "Store authorised files only if supported", requirement: "Confirm from source", ownership: "Customer", costNote: "Security and retention need review" },
          { name: "Demo URL", purpose: "Show a synthetic-data example", requirement: "Optional", ownership: "Member or customer by agreement", costNote: "Not connected yet" },
          { name: "Professional email and proposal", purpose: "One-to-one business communication", requirement: "Optional", ownership: "Member", costNote: "Avoid unnecessary paid tools" },
        ],
      },
      {
        id: "clinic-discovery",
        type: "discovery-questionnaire",
        title: "Understand the clinic",
        intro: "Use this questionnaire in a private conversation, then keep the clinic's answers in an appropriately secured customer-owned process—not in IncomeNow.",
        questions: [
          "How do new enquiries currently arrive?", "Who handles appointments?", "How are cancellations or no-shows managed?", "Who knows when follow-up is needed?", "What information must staff see?", "How are payments currently tracked?", "How many staff members need access?", "What roles and permissions are required?", "Which reports matter?", "Is existing data being imported?", "What needs to stay exactly as it is today?", "Who will manage the software after handover?", "What backup and recovery expectations exist?", "Which integrations are actually required?",
        ],
        privacyTitle: "Before using real clinic data",
        privacyBody: [
          "Clinic software can involve sensitive personal information. Confirm the actual data processed, permissions, security responsibilities, retention, backups, recovery, local requirements, and customer expectations before production use.",
          "This kit does not certify HIPAA, GDPR, DHA, DOH, MOHAP, or any other healthcare or security compliance. Use synthetic data for demonstrations and never put sensitive patient information into this questionnaire or an AI prompt.",
        ],
      },
      {
        id: "clinic-delivery",
        type: "action-plan",
        title: "Deliver the project",
        stages: clinicPlan.stages,
      },
    ],
  },
  {
    id: "idea-003",
    displayNumber: "003",
    slug: "quotation-follow-up-automation",
    title: "Quotation Follow-up Automation",
    summary: "Create internal follow-up tasks after quotations are sent, without sending unreviewed messages to customers.",
    solutionType: "Automation",
    industries: ["Professional Services", "Home Services"],
    technicalRequirements: ["Make, Zapier, or n8n", "Authorised API access", "Workflow testing"],
    intendedCustomer: "Service businesses that send tailored quotations",
    proposedBusinessModel: "Fixed-scope workflow setup with optional maintenance",
    readiness: "Setup ready",
    marketEvidence: "Not yet validated",
    addedOrder: 4,
    published: false,
    detailAvailable: true,
    implementationPlanVersion: automationPlan.version,
    previewVariant: "automation",
    coverArt: {
      src: "/artwork/ideas/quotation-follow-up-automation.webp",
      alt: "A quotation folder connected to a task card, calendar, and clock",
      position: "50% 50%",
    },
    publicCoverArt: {
      src: "/artwork/marketing/modern/automation-kit.webp",
      alt: "A clean quotation, calendar, task, and completion workflow",
      position: "50% 50%",
    },
    cardNote: "Tool compatibility requires verification",
    resources: [
      { id: "automation-flow", label: "Workflow example", type: "workflow", availability: "sample", description: "Illustrative orchestration pattern; no tools are connected." },
      { id: "automation-guide", label: "Setup guide", type: "guide", availability: "sample", description: "Connection, permission, and rate-limit guidance." },
      { id: "automation-tests", label: "Testing checklist", type: "checklist", availability: "sample", description: "Normal, failure, and duplicate-prevention cases." },
      { id: "automation-map", label: "Field-mapping worksheet", type: "worksheet", availability: "sample", description: "Map quotation IDs, statuses, owners, and dates." },
    ],
    sections: [
      {
        id: "automation-opportunity",
        type: "overview",
        title: "The opportunity",
        body: ["This idea connects quotation records with an internal follow-up process using tools the customer has authorised.", "The sample creates staff tasks and audit entries; it does not automatically message customers."],
        friction: "Teams manually scan accounting software or spreadsheets, causing delayed or duplicate follow-up and poor pipeline visibility.",
        validation: "Document where quotations are recorded, how replies are tracked, and who owns the next action before configuring any integration.",
        businessModel: "A fixed-scope configuration project followed by an optional maintenance agreement for schema and connection changes.",
      },
      {
        id: "automation-workflow",
        type: "workflow",
        title: "See how the workflow could work",
        description: "An illustrative weekday check evaluates quotation state and creates one internal task when the agreed conditions are met.",
        steps: [
          { id: "flow-source", title: "Quotation record", detail: "A stable quote ID is marked Sent in the agreed source." },
          { id: "flow-offset", title: "Follow-up offset", detail: "The due threshold is calculated from the sent date." },
          { id: "flow-check", title: "Scheduled check", detail: "The workflow queries due quotations on weekdays." },
          { id: "flow-condition", title: "Status evaluation", detail: "Only quotations still awaiting a recorded reply continue.", condition: "Continue when status remains pending" },
          { id: "flow-task", title: "Internal task", detail: "Create one task for the assigned employee and write an audit entry." },
        ],
        safeguard: "A unique quotation ID plus follow-up event key prevents duplicate tasks when a scheduler retries.",
      },
      {
        id: "automation-plan",
        type: "action-plan",
        title: "Configure, test, and hand over",
        stages: automationPlan.stages,
      },
      { id: "automation-resources", type: "resources", title: "Workflow resources", intro: "Every resource is a sample record in this preview and has no connected download.", resourceIds: ["automation-flow", "automation-map", "automation-guide", "automation-tests"] },
      {
        id: "automation-discovery",
        type: "customer-discovery",
        title: "Find a workflow worth improving",
        audiences: ["Consultancies", "Specialty trades", "Digital agencies", "Fabrication shops"],
        questions: ["Where do quotations live after they are sent?", "Who owns the next action when a quote goes cold?", "Which existing tools must remain in use?"],
        guidance: "Confirm access rights, third-party subscription costs, and maintenance responsibilities in writing before implementation.",
      },
      { id: "automation-limitations", type: "updates-limitations", title: "Updates and important notes", notes: ["No production workflow or customer messaging is connected.", "Compatibility, authentication, rate limits, and field schemas must be verified in each customer environment."] },
    ],
  },
  {
    id: "idea-004",
    displayNumber: "004",
    slug: "local-service-lead-generation",
    title: "Local-Service Lead Website",
    summary: "Explore a local website model that connects visitor enquiries with suitable service providers.",
    solutionType: "Lead-generation website",
    industries: ["Home Services", "Local Services"],
    technicalRequirements: ["Responsive website", "Form handling", "Provider routing", "Privacy review"],
    intendedCustomer: "Visitors seeking a local service and providers seeking suitable enquiries",
    proposedBusinessModel: "Website setup and provider-partnership service",
    readiness: "Concept ready",
    marketEvidence: "Discovery in progress",
    addedOrder: 3,
    published: false,
    detailAvailable: true,
    implementationPlanVersion: leadPlan.version,
    previewVariant: "website",
    coverArt: {
      src: "/artwork/ideas/local-service-lead-generation.webp",
      alt: "A service van and technician connected to a mobile enquiry interface",
      position: "50% 50%",
    },
    publicCoverArt: {
      src: "/artwork/marketing/modern/lead-website-kit.webp",
      alt: "A modern enquiry website connected to location pins and a service van",
      position: "50% 50%",
    },
    cardNote: "Research before building",
    resources: [
      { id: "lead-template", label: "Site template", type: "template", availability: "sample", description: "Sample page and enquiry-flow structure; no downloadable template is connected." },
      { id: "lead-research", label: "Research worksheet", type: "worksheet", availability: "sample", description: "Service-area and search-intent research prompts." },
      { id: "lead-partner", label: "Partner guide", type: "guide", availability: "sample", description: "Provider interview and handoff checklist." },
      { id: "lead-enquiry", label: "Enquiry checklist", type: "checklist", availability: "sample", description: "Consent, routing, and response-time checks." },
    ],
    sections: [
      {
        id: "lead-opportunity",
        type: "overview",
        title: "The opportunity",
        body: ["The sample separates two audiences: visitors who need a service and providers who may accept relevant enquiries.", "The idea should begin with local demand and partner discovery, not a generic directory build."],
        friction: "Visitors struggle to compare local providers while small operators often rely on inconsistent referrals and slow enquiry handling.",
        validation: "Research one service category and postcode cluster, then interview both recent buyers and at least five potential provider partners.",
        businessModel: "A scoped website and enquiry-handling service. Partner terms and any commercial model remain to be validated.",
      },
      {
        id: "lead-demo",
        type: "demo-preview",
        title: "Preview the visitor and provider journey",
        description: "The wireframe demonstrates service-area entry, a focused enquiry form, and a provider handoff. It does not submit or route real enquiries.",
        variant: "website",
        metrics: [
          { label: "Visitor steps", value: "3" },
          { label: "Provider handoff", value: "Manual" },
          { label: "Live forms", value: "0" },
        ],
      },
      {
        id: "lead-plan",
        type: "action-plan",
        title: "Research and prepare the service",
        stages: leadPlan.stages,
      },
      { id: "lead-resources", type: "resources", title: "Website and enquiry resources", intro: "These sample resources describe the intended kit. Nothing is downloadable or connected in Phase 1.", resourceIds: ["lead-template", "lead-research", "lead-partner", "lead-enquiry"] },
      {
        id: "lead-discovery",
        type: "customer-discovery",
        title: "Research both sides of the marketplace",
        audiences: ["Visitors who recently hired a local provider", "Independent local service businesses", "Trade associations and referral partners"],
        questions: ["What made a provider feel trustworthy?", "Which details determine whether an enquiry is worth accepting?", "How quickly must a provider respond?"],
        guidance: "Do not collect real enquiries until consent, retention, partner routing, and response ownership are documented.",
      },
      { id: "lead-limitations", type: "updates-limitations", title: "Updates and important notes", notes: ["The site preview uses fictional records and no real form endpoint.", "Demand, partner appetite, commercial terms, and data handling remain unvalidated."] },
    ],
  },
  {
    id: "idea-005",
    displayNumber: "005",
    slug: "supplier-research-service",
    title: "Supplier Research Service",
    summary: "Package structured supplier discovery and research for small manufacturing businesses.",
    solutionType: "Digital service",
    industries: ["Business Services", "Manufacturing"],
    technicalRequirements: ["Research workflow", "Spreadsheet templates"],
    intendedCustomer: "Small manufacturing and product businesses",
    proposedBusinessModel: "Scoped research engagement",
    readiness: "Concept ready",
    marketEvidence: "Not yet validated",
    addedOrder: 2,
    published: false,
    detailAvailable: false,
    fixtureLabel: "Preview only — full kit not yet published",
    previewVariant: "scorecard",
    coverArt: {
      src: "/artwork/ideas/supplier-research-service.webp",
      alt: "Supplier packages, material samples, and a structured comparison board",
      position: "50% 50%",
    },
    cardNote: "Research-service concept",
    resources: [
      { id: "supplier-brief", label: "Sample brief", type: "template", availability: "not-connected", description: "Fixture label only." },
      { id: "supplier-check", label: "Research checklist", type: "checklist", availability: "not-connected", description: "Fixture label only." },
      { id: "supplier-proposal", label: "Proposal template", type: "template", availability: "not-connected", description: "Fixture label only." },
    ],
    sections: [],
  },
  {
    id: "idea-034",
    displayNumber: "034",
    slug: "rental-property-management-tool",
    title: "Rental Property Management Tool",
    summary: "A lightweight multi-unit portal concept for independent landlords managing repairs and reminders.",
    solutionType: "Web tool",
    industries: ["Real Estate"],
    technicalRequirements: ["Next.js", "Database", "Role-based access"],
    intendedCustomer: "Independent multi-unit landlords",
    proposedBusinessModel: "Configured web application",
    readiness: "Concept ready",
    marketEvidence: "Not yet validated",
    addedOrder: 1,
    published: false,
    detailAvailable: false,
    fixtureLabel: "Preview only — full kit not yet published",
    previewVariant: "property",
    coverArt: {
      src: "/artwork/ideas/rental-property-management-tool.webp",
      alt: "A small apartment building model with keys, maintenance tools, and tenant cards",
      position: "50% 50%",
    },
    cardNote: "Requires tenancy workflow review",
    resources: [
      { id: "property-demo", label: "Demo", type: "demo", availability: "not-connected", description: "Fixture label only." },
      { id: "property-source", label: "Source code", type: "source", availability: "not-connected", description: "Fixture label only." },
      { id: "property-guide", label: "Setup guide", type: "guide", availability: "not-connected", description: "Fixture label only." },
    ],
    sections: [],
  },
];

export const ideas = ideasSchema.parse(rawIdeas);

export const publishedIdeas = ideas.filter((idea) => idea.published);
export const detailedIdeas = publishedIdeas.filter((idea) => idea.detailAvailable);

export function getIdeaBySlug(slug: string) {
  return ideas.find((idea) => idea.slug === slug);
}

export function getIdeaById(id: string) {
  return ideas.find((idea) => idea.id === id);
}
