import { ideasSchema, type Idea } from "./idea-schema";
import { getCurrentProjectPlan } from "./project-plans";

const crmPlan = getCurrentProjectPlan("idea-001");
const automationPlan = getCurrentProjectPlan("idea-003");
const leadPlan = getCurrentProjectPlan("idea-004");

if (!crmPlan || !automationPlan || !leadPlan) {
  throw new Error("Detailed ideas require trusted implementation plans.");
}

const rawIdeas: Idea[] = [
  {
    id: "idea-001",
    displayNumber: "001",
    slug: "pergola-quotation-follow-up-crm",
    title: "Pergola Quotation & Follow-up CRM",
    summary: "Organise enquiries, site visits, quotations, and installation follow-ups for high-margin outdoor construction work.",
    solutionType: "Custom CRM",
    industries: ["Home Services", "Outdoor Construction"],
    technicalRequirements: ["TypeScript", "React", "Database configuration", "Email or SMS integration"],
    intendedCustomer: "Pergola installers, timber framing shops, and outdoor-living contractors",
    proposedBusinessModel: "One-off implementation with optional managed support",
    readiness: "Sample blueprint",
    marketEvidence: "Not yet validated",
    addedOrder: 6,
    detailAvailable: true,
    implementationPlanVersion: crmPlan.version,
    previewVariant: "pipeline",
    cardNote: "Estimated launch: 2 weeks",
    resources: [
      { id: "crm-demo", label: "Demo", type: "demo", availability: "not-connected", description: "Illustrative CRM preview using fictional records." },
      { id: "crm-source", label: "Source code", type: "source", availability: "not-connected", description: "A production-ready source package has not been prepared or verified." },
      { id: "crm-guide", label: "Setup guide", type: "guide", availability: "not-connected", description: "A deployment guide still needs to be written against a real, tested implementation." },
      { id: "crm-discovery", label: "Discovery script", type: "script", availability: "not-connected", description: "The written questions below are available; a separate downloadable interview worksheet is not connected." },
    ],
    sections: [
      {
        type: "overview",
        title: "The opportunity",
        body: [
          "This starter investigates a tailored CRM for pergola installers, timber-framing shops, and outdoor-living contractors that handle site enquiries, measurements, multi-option quotations, deposits, installation scheduling, and follow-up.",
          "Treat the workflow as a suggested investigation path, not a verified description of every contractor. Map the buyer’s current tools, hand-offs, delays, and ownership before proposing software.",
          "The proposed offer is a scoped CRM setup with optional support. It is not a proven commercial package: no buyer interviews, sales, live deployments, or willingness-to-pay evidence are documented in this repository.",
        ],
        friction: "Potential friction to investigate: measurements and quote options can move between inboxes, paper notes, spreadsheets, and staff, while responsibility for the next follow-up remains unclear.",
        validation: "Ask contractors to walk through recent enquiries from first contact to final outcome. Confirm where data is re-entered, which quote details change, who owns each follow-up, what customers ask repeatedly, and which mistakes have a measurable operational cost.",
        businessModel: "Proposed offer: a deliberately scoped setup and handover project, with optional hosting or support only when responsibilities, data protection, third-party costs, response times, and change limits are written down.",
      },
      {
        type: "workflow",
        title: "Suggested contractor workflow to investigate",
        description: "Use this sequence as an interview and demonstration outline. It is not a verified product capability or a claim about a particular contractor’s process.",
        steps: [
          { id: "crm-enquiry", title: "Capture the enquiry", detail: "Record contact details, site location, requested structure, timing, and consented communication channel." },
          { id: "crm-qualification", title: "Qualify the request", detail: "Confirm service area, decision-maker, indicative scope, site constraints, and whether a survey is warranted." },
          { id: "crm-survey", title: "Prepare the site visit", detail: "Assign an owner and collect measurements, access notes, photos, material preferences, and open questions." },
          { id: "crm-quote", title: "Draft and review options", detail: "Track the quotation version, assumptions, exclusions, approval owner, sent date, and the next agreed action." },
          { id: "crm-follow-up", title: "Follow up deliberately", detail: "Create staff reminders tied to the quote and record the outcome without sending unreviewed automated promises.", condition: "Continue only with the contractor’s approved timing and communication process" },
          { id: "crm-handover", title: "Hand over won work", detail: "Transfer the accepted scope, customer decisions, deposit state, scheduling constraints, and unresolved risks to delivery." },
        ],
        safeguard: "Keep access roles, backups, retention, message approval, and audit needs in the implementation scope. Do not place real customer data in an illustrative demonstration.",
      },
      {
        type: "demo-preview",
        title: "Explore the example system",
        description: "The illustrative demonstration uses fictional records to walk from a new enquiry through qualification, site visit, quote review, follow-up, and won-work handover. It shows the conversation to prepare; no working customer CRM, live form, automation, or messaging service exists in this build.",
        variant: "crm",
        metrics: [
          { label: "Enquiries", value: "14" },
          { label: "Quotes due", value: "8" },
          { label: "Site visits", value: "5" },
        ],
      },
      {
        type: "action-plan",
        title: "Turn this idea into a project",
        stages: crmPlan.stages,
      },
      { type: "resources", title: "Implementation resources", intro: "Sample labels describe the intended kit. Downloads and external demo environments are not connected.", resourceIds: ["crm-demo", "crm-source", "crm-guide", "crm-discovery"] },
      {
        type: "customer-discovery",
        title: "Who to approach and what to discuss",
        audiences: ["Owner-operators who quote and install", "Sales or survey staff in pergola businesses", "Operations staff who receive won-work handovers", "Veranda, awning, and outdoor-carpentry specialists with comparable workflows"],
        questions: [
          "Please walk through the last enquiry that became a job. Which records and people were involved?",
          "Which measurements, options, exclusions, and approvals must be correct before a quotation is sent?",
          "How do you know which quotes are awaiting a reply, and who owns the next action?",
          "Where is information copied between email, messaging, paper, spreadsheets, accounting tools, or calendars?",
          "Which delays or mistakes have a real operational cost, and how is that cost observed?",
          "What would a useful demonstration need to reflect before it felt relevant rather than generic?",
          "Which systems must remain the source of truth, and what integrations are actually authorised?",
          "Who would maintain users, backups, templates, message rules, and process changes after handover?",
        ],
        guidance: "After interviews, write a narrow problem statement and demonstration scenario using fictional data. Define the proposed offer with inclusions, exclusions, acceptance checks, handover responsibilities, support boundaries, third-party costs, and a change process. Prepare outreach around the observed workflow—not unsupported savings or sales claims—and test interest before custom development.",
      },
      { type: "updates-limitations", title: "Starter readiness and operating responsibilities", notes: [
        "Documented evidence: none yet. Buyer interviews, workflow observations, demand, pricing, and willingness to pay still require real validation.",
        "Demonstration readiness: prepare a relevant fictional dataset and a working walkthrough before selling access; the current schematic is illustrative only.",
        "Product readiness: build and test the CRM, role permissions, validation, audit trail, backups, restore procedure, and error handling before handling customer data.",
        "Integration readiness: verify authorised APIs, rate limits, duplicate prevention, delivery failures, message approval, and third-party costs in the customer’s environment.",
        "Commercial readiness: approve access duration, taxes, refunds, support scope, hosting responsibility, data-processing terms, and final resource licence.",
        "Handover readiness: prepare acceptance tests, administrator guidance, credential transfer, support contacts, incident ownership, change control, and an exit/export path.",
      ] },
    ],
  },
  {
    id: "idea-002",
    displayNumber: "002",
    slug: "washing-machine-repair-crm",
    title: "Washing-Machine Repair CRM",
    summary: "Track technician routes, diagnostic reports, spare-part inventory, and post-service warranty milestones.",
    solutionType: "Custom CRM",
    industries: ["Repair Services"],
    technicalRequirements: ["Web application configuration"],
    intendedCustomer: "Independent appliance-repair teams",
    proposedBusinessModel: "Implementation service",
    readiness: "Concept ready",
    marketEvidence: "Not yet validated",
    addedOrder: 5,
    detailAvailable: false,
    fixtureLabel: "Library fixture — detail not included in Phase 1",
    previewVariant: "dispatch",
    cardNote: "Requires workflow discovery",
    resources: [
      { id: "repair-demo", label: "Demo", type: "demo", availability: "not-connected", description: "Fixture label only." },
      { id: "repair-source", label: "Source code", type: "source", availability: "not-connected", description: "Fixture label only." },
      { id: "repair-guide", label: "Sales guide", type: "guide", availability: "not-connected", description: "Fixture label only." },
    ],
    sections: [],
  },
  {
    id: "idea-003",
    displayNumber: "003",
    slug: "quotation-follow-up-automation",
    title: "Quotation Follow-up Automation",
    summary: "Create internal follow-up tasks after quotations are sent, without sending unreviewed messages to customers.",
    solutionType: "Automation",
    industries: ["Professional Services", "Home Services"],
    technicalRequirements: ["Make, Zapier, or n8n", "Authorised API access", "Workflow testing"],
    intendedCustomer: "Service businesses that send tailored quotations",
    proposedBusinessModel: "Fixed-scope workflow setup with optional maintenance",
    readiness: "Setup ready",
    marketEvidence: "Not yet validated",
    addedOrder: 4,
    detailAvailable: true,
    implementationPlanVersion: automationPlan.version,
    previewVariant: "automation",
    cardNote: "Make / n8n compatible",
    resources: [
      { id: "automation-flow", label: "Workflow example", type: "workflow", availability: "sample", description: "Illustrative orchestration pattern; no tools are connected." },
      { id: "automation-guide", label: "Setup guide", type: "guide", availability: "sample", description: "Connection, permission, and rate-limit guidance." },
      { id: "automation-tests", label: "Testing checklist", type: "checklist", availability: "sample", description: "Normal, failure, and duplicate-prevention cases." },
      { id: "automation-map", label: "Field-mapping worksheet", type: "worksheet", availability: "sample", description: "Map quotation IDs, statuses, owners, and dates." },
    ],
    sections: [
      {
        type: "overview",
        title: "The opportunity",
        body: ["This idea connects quotation records with an internal follow-up process using tools the customer has authorised.", "The sample creates staff tasks and audit entries; it does not automatically message customers."],
        friction: "Teams manually scan accounting software or spreadsheets, causing delayed or duplicate follow-up and poor pipeline visibility.",
        validation: "Document where quotations are recorded, how replies are tracked, and who owns the next action before configuring any integration.",
        businessModel: "A fixed-scope configuration project followed by an optional maintenance agreement for schema and connection changes.",
      },
      {
        type: "workflow",
        title: "See how the workflow could work",
        description: "An illustrative weekday check evaluates quotation state and creates one internal task when the agreed conditions are met.",
        steps: [
          { id: "flow-source", title: "Quotation record", detail: "A stable quote ID is marked Sent in the agreed source." },
          { id: "flow-offset", title: "Follow-up offset", detail: "The due threshold is calculated from the sent date." },
          { id: "flow-check", title: "Scheduled check", detail: "The workflow queries due quotations on weekdays." },
          { id: "flow-condition", title: "Status evaluation", detail: "Only quotations still awaiting a recorded reply continue.", condition: "Continue when status remains pending" },
          { id: "flow-task", title: "Internal task", detail: "Create one task for the assigned employee and write an audit entry." },
        ],
        safeguard: "A unique quotation ID plus follow-up event key prevents duplicate tasks when a scheduler retries.",
      },
      {
        type: "action-plan",
        title: "Configure, test, and hand over",
        stages: automationPlan.stages,
      },
      { type: "resources", title: "Workflow resources", intro: "Every resource is a sample record in this preview and has no connected download.", resourceIds: ["automation-flow", "automation-map", "automation-guide", "automation-tests"] },
      {
        type: "customer-discovery",
        title: "Find a workflow worth improving",
        audiences: ["Consultancies", "Specialty trades", "Digital agencies", "Fabrication shops"],
        questions: ["Where do quotations live after they are sent?", "Who owns the next action when a quote goes cold?", "Which existing tools must remain in use?"],
        guidance: "Confirm access rights, third-party subscription costs, and maintenance responsibilities in writing before implementation.",
      },
      { type: "updates-limitations", title: "Updates and important notes", notes: ["No production workflow or customer messaging is connected.", "Compatibility, authentication, rate limits, and field schemas must be verified in each customer environment."] },
    ],
  },
  {
    id: "idea-004",
    displayNumber: "004",
    slug: "local-service-lead-generation",
    title: "Local-Service Lead Website",
    summary: "Explore a local website model that connects visitor enquiries with suitable service providers.",
    solutionType: "Lead-generation website",
    industries: ["Home Services", "Local Services"],
    technicalRequirements: ["Responsive website", "Form handling", "Provider routing", "Privacy review"],
    intendedCustomer: "Visitors seeking a local service and providers seeking suitable enquiries",
    proposedBusinessModel: "Website setup and provider-partnership service",
    readiness: "Concept ready",
    marketEvidence: "Discovery in progress",
    addedOrder: 3,
    detailAvailable: true,
    implementationPlanVersion: leadPlan.version,
    previewVariant: "website",
    cardNote: "Research before building",
    resources: [
      { id: "lead-template", label: "Site template", type: "template", availability: "sample", description: "Sample page and enquiry-flow structure; no downloadable template is connected." },
      { id: "lead-research", label: "Research worksheet", type: "worksheet", availability: "sample", description: "Service-area and search-intent research prompts." },
      { id: "lead-partner", label: "Partner guide", type: "guide", availability: "sample", description: "Provider interview and handoff checklist." },
      { id: "lead-enquiry", label: "Enquiry checklist", type: "checklist", availability: "sample", description: "Consent, routing, and response-time checks." },
    ],
    sections: [
      {
        type: "overview",
        title: "The opportunity",
        body: ["The sample separates two audiences: visitors who need a service and providers who may accept relevant enquiries.", "The idea should begin with local demand and partner discovery, not a generic directory build."],
        friction: "Visitors struggle to compare local providers while small operators often rely on inconsistent referrals and slow enquiry handling.",
        validation: "Research one service category and postcode cluster, then interview both recent buyers and at least five potential provider partners.",
        businessModel: "A scoped website and enquiry-handling service. Partner terms and any commercial model remain to be validated.",
      },
      {
        type: "demo-preview",
        title: "Preview the visitor and provider journey",
        description: "The wireframe demonstrates service-area entry, a focused enquiry form, and a provider handoff. It does not submit or route real enquiries.",
        variant: "website",
        metrics: [
          { label: "Visitor steps", value: "3" },
          { label: "Provider handoff", value: "Manual" },
          { label: "Live forms", value: "0" },
        ],
      },
      {
        type: "action-plan",
        title: "Research and prepare the service",
        stages: leadPlan.stages,
      },
      { type: "resources", title: "Website and enquiry resources", intro: "These sample resources describe the intended kit. Nothing is downloadable or connected in Phase 1.", resourceIds: ["lead-template", "lead-research", "lead-partner", "lead-enquiry"] },
      {
        type: "customer-discovery",
        title: "Research both sides of the marketplace",
        audiences: ["Visitors who recently hired a local provider", "Independent local service businesses", "Trade associations and referral partners"],
        questions: ["What made a provider feel trustworthy?", "Which details determine whether an enquiry is worth accepting?", "How quickly must a provider respond?"],
        guidance: "Do not collect real enquiries until consent, retention, partner routing, and response ownership are documented.",
      },
      { type: "updates-limitations", title: "Updates and important notes", notes: ["The site preview uses fictional records and no real form endpoint.", "Demand, partner appetite, commercial terms, and data handling remain unvalidated."] },
    ],
  },
  {
    id: "idea-005",
    displayNumber: "005",
    slug: "supplier-research-service",
    title: "Supplier Research Service",
    summary: "Package structured supplier discovery and research for small manufacturing businesses.",
    solutionType: "Digital service",
    industries: ["Business Services", "Manufacturing"],
    technicalRequirements: ["Research workflow", "Spreadsheet templates"],
    intendedCustomer: "Small manufacturing and product businesses",
    proposedBusinessModel: "Scoped research engagement",
    readiness: "Concept ready",
    marketEvidence: "Not yet validated",
    addedOrder: 2,
    detailAvailable: false,
    fixtureLabel: "Library fixture — detail not included in Phase 1",
    previewVariant: "scorecard",
    cardNote: "No-code service concept",
    resources: [
      { id: "supplier-brief", label: "Sample brief", type: "template", availability: "not-connected", description: "Fixture label only." },
      { id: "supplier-check", label: "Research checklist", type: "checklist", availability: "not-connected", description: "Fixture label only." },
      { id: "supplier-proposal", label: "Proposal template", type: "template", availability: "not-connected", description: "Fixture label only." },
    ],
    sections: [],
  },
  {
    id: "idea-034",
    displayNumber: "034",
    slug: "rental-property-management-tool",
    title: "Rental Property Management Tool",
    summary: "A lightweight multi-unit portal concept for independent landlords managing repairs and reminders.",
    solutionType: "Web tool",
    industries: ["Real Estate"],
    technicalRequirements: ["Next.js", "Database", "Role-based access"],
    intendedCustomer: "Independent multi-unit landlords",
    proposedBusinessModel: "Configured web application",
    readiness: "Concept ready",
    marketEvidence: "Not yet validated",
    addedOrder: 1,
    detailAvailable: false,
    fixtureLabel: "Library fixture — detail not included in Phase 1",
    previewVariant: "property",
    cardNote: "Requires tenancy workflow review",
    resources: [
      { id: "property-demo", label: "Demo", type: "demo", availability: "not-connected", description: "Fixture label only." },
      { id: "property-source", label: "Source code", type: "source", availability: "not-connected", description: "Fixture label only." },
      { id: "property-guide", label: "Setup guide", type: "guide", availability: "not-connected", description: "Fixture label only." },
    ],
    sections: [],
  },
];

export const ideas = ideasSchema.parse(rawIdeas);

export const detailedIdeas = ideas.filter((idea) => idea.detailAvailable);

export function getIdeaBySlug(slug: string) {
  return ideas.find((idea) => idea.slug === slug);
}

export function getIdeaById(id: string) {
  return ideas.find((idea) => idea.id === id);
}
